# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
