# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-03 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190503_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(),
        ),
    ]
