# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190503_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=200)),
                ('link', models.TextField()),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
    ]
