# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-07-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_stub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
